### ISSUE TITLE
Document Type Permissions: "Allow as root" mislabelled

### ISSUE THREAD

**Issue by leekelleher** [umbraco-community/spark-hackathon-2024#7]
In the Document Type's Permissions view, the option to allow a document-type to be used at the root level is mislabelled in English as "Allow **as** root, whereas it should be "Allow **at** root".

The corresponding localization key is `allowAsRootHeading`, and can be updated here:
https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/EmbeddedResources/Lang/en.xml#L1897

> [!NOTE]
> The localization key does have the typo in its name, but it is referenced elsewhere in the CMS, so for backwards-compatibility, it's probably best to leave the key alias alone and only update the text/label.

**Comment by LottePitcher** [comment]
@nul800sebastiaan is this still needed?

**Comment by leekelleher** [comment]
To note, I was meaning this as a v13 fix, as opposed to v14/Bellissima fix (which has already been corrected).
